# Generated by Django 4.1.1 on 2022-09-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeSupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
