# Generated by Django 4.1.1 on 2022-09-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeSupport', '0003_alter_signup_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AcmeSupport.department'),
        ),
    ]
