# Generated by Django 4.1.1 on 2022-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeSupport', '0004_alter_signup_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
